import json

# ─── MOVIE TITLES ───
MOVIE_TITLES = MOVIE_TITLES = [
    "9 to 5",
    "A League of Their Own",
    "An Education",
    "Argo",
    "As Good as It Gets",
    "Bend It Like Beckham",
    "Black Swan",
    "Brooklyn",
    "Carol",
    "Clueless",
    "Colette",
    "Crazy Rich Asians",
    "Divergent",
    "Eternal Sunshine of the Spotless Mind",
    "Frances Ha",
    "Frozen",
    "Ghostbusters (2016)",
    "Gone Girl",
    "Hidden Figures",
    "Inside Out",
    "Juno",
    "Lady Bird",
    "La La Land",
    "Legally Blonde",
    "Little Women (2019)",
    "Lost in Translation",
    "Mamma Mia!",
    "Mrs. Doubtfire",
    "My Big Fat Greek Wedding",
    "Nashville",
    "Ocean’s 8",
    "Portrait of a Lady on Fire",
    "Promising Young Woman",
    "Saving Mr. Banks",
    "Sense and Sensibility",
    "Shall We Dance? (2004)",
    "Suffragette",
    "Sugar & Spice",
    "Sunshine Cleaning",
    "The Babadook",
    "The Favourite",
    "The Handmaiden",
    "The Kids Are All Right",
    "Thelma & Louise",
    "Thirteen",
    "To All the Boys I’ve Loved Before",
    "Toni Erdmann",
    "Trainwreck",
    "Vanity Fair",
    "Vera Drake",
    "Whale Rider",
    "Wonder Woman",
    "Wonder Woman 1984",
    "Zero Dark Thirty",
    "Zootopia",
    "20th Century Women",
    "50/50",
    "A Simple Favor",
    "American Psycho",
    "Amber Waves",
    "Amélie",
    "An Unmarried Woman",
    "Angels in America",
    "April and the Extraordinary World",
    "August: Osage County",
    "Babette’s Feast",
    "Baby Mama",
    "Bad Moms",
    "Barbara",
    "Before Sunrise",
    "Before Sunset",
    "Before Midnight",
    "Belle",
    "Big Eyes",
    "Big Hero 6",
    "Big Night",
    "Billy Elliot",
    "Bird Box",
    "Blue Jasmine",
    "Blue Is the Warmest Colour",
    "Bridget Jones’s Diary",
    "Brooklyn (2015)",
    "Butterfly Kiss",
    "Captain Marvel",
    "Catch Me If You Can",
    "Changeling",
    "Chocolat (2000)",
    "Closer",
    "Colette (2018)",
    "Crazy, Stupid, Love",
    "D.E.B.S.",
    "Diary of a Teenage Girl",
    "Duma",
    "Easy A",
    "Eat Pray Love",
    "Fever Pitch",
    "Filth",
    "For Colored Girls",
    "Forgetting Sarah Marshall",
    "Frozen II",
    "G.I. Jane",
    "Game Night",
    "Girl, Interrupted",
    "Girlhood",
    "Hanna",
    "Her",
    "I Am Woman",
    "I, Tonya",
    "Ice Princess",
    "If Beale Street Could Talk",
    "In the Mood for Love",
    "Instant Family",
    "Iron Jawed Angels",
    "It’s Complicated",
    "Jackie",
    "Jane Eyre (2011)",
    "Jennifer’s Body",
    "Joy",
    "Jurassic Park",
    "Just Mercy",
    "Julie & Julia",
    "Kiki’s Delivery Service",
    "Ladyhawke",
    "La La Land",
    "Lara Croft: Tomb Raider",
    "Let Me In",
    "Like Crazy",
    "Lion",
    "Little Women (1994)",
    "Live Free or Die Hard",
    "Lolita (1997)",
    "Looper",
    "Loving",
    "Lucy",
    "Mad Max: Fury Road",
    "Maid in Manhattan",
    "Maleficent",
    "Man on Fire",
    "Maggie’s Plan",
    "Magic Mike",
    "Mamma Mia!",
    "Molly’s Game",
    "Moonlight",
    "Moonrise Kingdom",
    "Morning Glory",
    "Mr. & Mrs. Smith",
    "My Summer of Love",
    "Mystic River",
    "Nashville (1975)",
    "Neighbors",
    "Never Let Me Go",
    "Nicole & O.J.",
    "Obvious Child",
    "Ocean’s Eight",
    "Once",
    "One Day",
    "Out of Africa",
    "Paddington 2",
    "Pan’s Labyrinth",
    "Paper Moon",
    "Paris, je t’aime",
    "Paterson",
    "Penelope",
    "Persepolis",
    "Pieces of a Woman",
    "Pitch Perfect",
    "Pleasantville",
    "Pocahontas",
    "Precious",
    "Pride & Prejudice (2005)",
    "Prometheus",
    "Proof",
    "Pulp Fiction",
    "Queen of Katwe",
    "Queen & Slim",
    "Rachel Getting Married",
    "Raw",
    "Ready or Not",
    "Room",
    "Rosemary’s Baby",
    "Rough Night",
    "Runaway Bride",
    "Safe Haven",
    "Salt",
    "Saving Private Ryan",
    "Scream",
    "Scott Pilgrim vs. the World",
    "Se7en",
    "Serendipity",
    "Sideways",
    "Silkwood",
    "Sing Street",
    "Some Like It Hot",
    "Sophie’s Choice",
    "Soul",
    "Sound of Metal",
    "Southside with You",
    "Spotlight",
    "Stardust",
    "Still Alice",
    "Straight Outta Compton",
    "Straw Dogs",
    "Summer of ’42",
    "Sunset Boulevard",
    "Suspiria",
    "Swing Time",
    "Take This Waltz",
    "Tár",
    "Tea with Mussolini",
    "Teenage Mutant Ninja Turtles",
    "The Adjustment Bureau",
    "The Babadook",
    "The Blair Witch Project",
    "The Danish Girl",
    "The Dressmaker",
    "The Edge of Seventeen",
    "The Favourite",
    "The Florida Project",
    "The Fundamentals of Caring",
    "The Girl with the Dragon Tattoo",
    "The Greatest Showman",
    "The Handmaid’s Tale",
    "The Invisible Man",
    "The Joy Luck Club",
    "The Last Black Man in San Francisco",
    "The Light Between Oceans",
    "The Lobster",
    "The Lunchbox",
    "The Martian",
    "The Matrix",
    "The Piano",
    "The Shape of Water",
]


# ─── DEFAULT FLAGS ───
DEFAULT_FLAGS = {
    "femaleLead": False,
    "maleLead": False,
    "womenDirector": False,
    "womenScreenwriter": True,
    "oscarWinner": False,
    "cannesWinner": False
}

# ─── BUILD FUNCTIONS ───
def build_genre_map(titles):
    return { title: [] for title in titles }

def build_movies(genres_map):
    movies = []
    for title, genres in genres_map.items():
        movie = {"title": title, "genres": genres, **DEFAULT_FLAGS}
        movies.append(movie)
    return movies

if __name__ == "__main__":
    # Step 1: generate the genre‐map stub
    GENRE_MAP = build_genre_map(MOVIE_TITLES)
    with open("genre_map_stub.json", "w", encoding="utf-8") as f:
        json.dump({"GENRE_MAP": GENRE_MAP}, f, indent=2, ensure_ascii=False)
    print(f"Wrote genre_map_stub.json with {len(GENRE_MAP)} titles.")

    # Step 2: once you’ve filled in genre_map_stub.json, uncomment below to create your full movies.json
    """
    with open("genre_map_stub.json", "r", encoding="utf-8") as f:
        data = json.load(f)
        GENRE_MAP = data["GENRE_MAP"]
    movies = build_movies(GENRE_MAP)
    with open("movies.json", "w", encoding="utf-8") as out:
        json.dump(movies, out, indent=2, ensure_ascii=False)
    print(f"Generated movies.json with {len(movies)} entries.")
    """
